version: 2
jobs:
  build:
    working_directory: ~/ikuradon
    docker:
      - image: circleci/node:10.16.3
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - deploy:
          name: Expo CDN Auto Publish
          command: yarn run ci-publish
